### ISSUE TITLE
"Transparent" spectrogram with outline amplitude shape

### ISSUE THREAD

**Issue by SourMan99** [p-rocha/SoundShape#4]
I am trying to change the colour of the threeDspectro to only look at the amplitude envelope shape and not the intensity... is there a way to change the colours/fill colour to be transparent and see only the outline of the wave?

**Comment by p-rocha** [comment]
Hi there, 

There're a couple of ways to look at the amplitude envelope shape. The simplest is using `spectro` function from `seewave` package with arguments `cont=TRUE`, `contlevels = seq(-25, -25, 1)` and `collevels = seq(-1, 0, 0.1`) 

`seewave::spectro(cuvieri, flim=c(0, 4), tlim = c(0, 0.5), grid=F, cont=TRUE, contlevels = seq(-25, -25, 1), collevels = seq(-1, 0, 0.1))`

![image](https://user-images.githubusercontent.com/51244423/208851295-82e87ce7-8f95-47e3-aac0-f5bcd9200cb3.png)

`contlevels` specify the relative amplitude value at which you intend to look at envelope shape.
`collevels = seq(-1, 0, 0.1)` is the smallest accepted value for colours, effectively creating a "transparent" plot.

Alternatively, if you want to look at the shape using `threeDspectro` there will be a bit more coding using functions from `plot3D` package. I'd recommend you have a look at topic 4.3 from [SoundShape's Getting Started vignette](https://github.com/p-rocha/SoundShape/blob/1.1.9/vignettes/Getting-started.Rmd).

Hope it helps!
Pedro

**Comment by SourMan99** [comment]
Hello, thank you for getting back to me.
I went over section 4.3 but I was not sure how it was relevant in making a transparent 3D spectrogram. Would you be able to assist me with the arguments I need to add for `threeDspectro`?

**Comment by p-rocha** [comment]
### Plot "transparent" 3D spectrogram 
You can create a fully transparent 3D spectrogram using `threeDspectro` with the argument `color = FALSE`:

`threeDspectro(kroyeri, flim=c(0, 4), tlim=c(0.2, 1), color = FALSE)`
![transparent 1](https://user-images.githubusercontent.com/51244423/215372840-9af0c3cb-de20-4855-913d-a897d2ae5bfa.png)

### Add curve of relative amplitude
To add the relative amplitude contour, you'll need to use functions from the `seewave` and `plot3D` packages, which was adapted from section 4.3 from [SoundShape's Getting Started vignette](https://github.com/p-rocha/SoundShape/blob/1.1.9/vignettes/Getting-started.Rmd):

Get spectro data
`s.kro <- seewave::spectro(kroyeri, tlim=c(0.2, 1), flim=c(0, 4), plot=F)`

Remove -Inf values and define value for relative amplitude 
`for(i in 1:length(s.kro$amp)){if(s.kro$amp[i] == -Inf |s.kro$amp[i] <= -40) {s.kro$amp[i] <- -40}}`

Add curve of relative amplitude
`plot3D::contour3D(x=s.kro$time, y=s.kro$freq, colvar=t(s.kro$amp), z=-25, plot=T, add=T, addbox=F, col="black", lwd=1.9, nlevels=2, dDepth=0.25)`

![curve 1](https://user-images.githubusercontent.com/51244423/215373282-7184a80c-b32e-4eaa-8d39-c07a92f17e62.png)

### Rotate 3D spectro for different views:
Manually done using arguments `rotate.Xaxis` and `rotate.Yaxis`:
`threeDspectro(kroyeri, flim=c(0, 4), tlim=c(0.2, 1), color = FALSE, rotate.Xaxis = 90)`

Add curve:
`plot3D::contour3D(x=s.kro$time, y=s.kro$freq, colvar=t(s.kro$amp), z=-25, plot=T, add=T, addbox=F, col="black", lwd=1.9, nlevels=1, dDepth=0.25)`

![curve 2](https://user-images.githubusercontent.com/51244423/215374927-f8a30b60-036c-4cdc-804a-a98c7a40b29a.png)


### Change value of relative amplitude:
Fairly complex and prone to errors as the functions were not meant to do this. 
If in trouble, try different values of relative amplitude in the `for` loop, and/or different values of `nlevels` when plotting the curve with `plot3D::contour3D`:

`s.kro <- seewave::spectro(kroyeri, tlim=c(0.2, 1), flim=c(0, 4), plot=F)`
`for(i in 1:length(s.kro$amp)){if(s.kro$amp[i] == -Inf |s.kro$amp[i] <= -25) {s.kro$amp[i] <- -25}}`
`threeDspectro(kroyeri, flim=c(0, 4), tlim=c(0.2, 1), color = FALSE, rotate.Xaxis = 0, rotate.Yaxis = 90)`
`plot3D::contour3D(x=s.kro$time, y=s.kro$freq, colvar=t(s.kro$amp), z=-25,plot=T, add=T, addbox=F, col="black", lwd=1.9, nlevels=1, dDepth=0.25)`

![curve 3](https://user-images.githubusercontent.com/51244423/215375542-571e1d7b-6706-4bee-b3d4-0919ef477e94.png)

**Comment by SourMan99** [comment]
Thank you for your quick response, however, this is not quite what I am hoping for. Attached is an image of what I am looking to achieve. Is there a way to achieve something similar using `threeDspectro`?
<img width="309" alt="image" src="https://user-images.githubusercontent.com/119948674/215793631-9dcee3c0-69d3-454d-9d90-ba66adb6a88a.png">
